INSERT INTO MEMBER (MEMBER_ID, MEMBERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1);

INSERT INTO AUTH (AUTH_NAME) values ('ROLE_MEMBER');
INSERT INTO AUTH (AUTH_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (MEMBER_ID, AUTH_NAME) values (1, 'ROLE_MEMBER');
INSERT INTO USER_AUTHORITY (MEMBER_ID, AUTH_NAME) values (1, 'ROLE_ADMIN');